### ISSUE TITLE
12GB VRAM not enough? RTX 3060 - Linux Mint 21.1

### ISSUE THREAD

**Issue by wh33t** [timothybrooks/instruct-pix2pix#41] opened 2023-01-24 00:54 UTC
When I try to generate an image from a 512x512 image (tried both jpg and png), I get the following error output. The error appears to be roughly the same whether I use the gradio webui or just straight from the command line. Any idea what might be causing this?

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/wh33t/instruct-pix2pix/edit_cli.py:128 in <module>                                         │
│                                                                                                  │
│   125                                                                                            │
│   126                                                                                            │
│   127 if __name__ == "__main__":                                                                 │
│ ❱ 128 │   main()                                                                                 │
│   129                                                                                            │
│                                                                                                  │
│ /home/wh33t/instruct-pix2pix/edit_cli.py:98 in main                                              │
│                                                                                                  │
│    95 │   │   input_image.save(args.output)                                                      │
│    96 │   │   return                                                                             │
│    97 │                                                                                          │
│ ❱  98 │   with torch.no_grad(), autocast("cuda"), model.ema_scope():                             │
│    99 │   │   cond = {}                                                                          │
│   100 │   │   cond["c_crossattn"] = [model.get_learned_conditioning([args.edit])]                │
│   101 │   │   input_image = 2 * torch.tensor(np.array(input_image)).float() / 255 - 1            │
│                                                                                                  │
│ /home/wh33t/anaconda3/envs/ip2p/lib/python3.8/contextlib.py:113 in __enter__                     │
│                                                                                                  │
│   110 │   │   # they are only needed for recreation, which is not possible anymore               │
│   111 │   │   del self.args, self.kwds, self.func                                                │
│   112 │   │   try:                                                                               │
│ ❱ 113 │   │   │   return next(self.gen)                                                          │
│   114 │   │   except StopIteration:                                                              │
│   115 │   │   │   raise RuntimeError("generator didn't yield") from None                         │
│   116                                                                                            │
│                                                                                                  │
│ /home/wh33t/instruct-pix2pix/./stable_diffusion/ldm/models/diffusion/ddpm_edit.py:185 in         │
│ ema_scope                                                                                        │
│                                                                                                  │
│    182 │   @contextmanager                                                                       │
│    183 │   def ema_scope(self, context=None):                                                    │
│    184 │   │   if self.use_ema:                                                                  │
│ ❱  185 │   │   │   self.model_ema.store(self.model.parameters())                                 │
│    186 │   │   │   self.model_ema.copy_to(self.model)                                            │
│    187 │   │   │   if context is not None:                                                       │
│    188 │   │   │   │   print(f"{context}: Switched to EMA weights")                              │
│                                                                                                  │
│ /home/wh33t/instruct-pix2pix/./stable_diffusion/ldm/modules/ema.py:62 in store                   │
│                                                                                                  │
│   59 │   │     parameters: Iterable of `torch.nn.Parameter`; the parameters to be                │
│   60 │   │   │   temporarily stored.                                                             │
│   61 │   │   """                                                                                 │
│ ❱ 62 │   │   self.collected_params = [param.clone() for param in parameters]                     │
│   63 │                                                                                           │
│   64 │   def restore(self, parameters):                                                          │
│   65 │   │   """                                                                                 │
│                                                                                                  │
│ /home/wh33t/instruct-pix2pix/./stable_diffusion/ldm/modules/ema.py:62 in <listcomp>              │
│                                                                                                  │
│   59 │   │     parameters: Iterable of `torch.nn.Parameter`; the parameters to be                │
│   60 │   │   │   temporarily stored.                                                             │
│   61 │   │   """                                                                                 │
│ ❱ 62 │   │   self.collected_params = [param.clone() for param in parameters]                     │
│   63 │                                                                                           │
│   64 │   def restore(self, parameters):                                                          │
│   65 │   │   """                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 11.75 GiB total capacity; 9.65 GiB already allocated; 30.00 MiB free; 9.83 GiB reserved in total by PyTorch) If reserved memory is >> allocated 
memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by redcartel243** [comment] 2023-01-24 03:54
I am getting the same error

**Comment by wh33t** [comment] 2023-01-24 05:17
> I am getting the same error

What OS/GPU do you have?

**Comment by Dreamz-Dziner** [comment] 2023-01-24 11:01
So relieved to find that I am not the only one scratching my head over the exact error from 2-3hrs. Wish somebody had a solution.

**Comment by redcartel243** [comment] 2023-01-24 14:24
> > I am getting the same error
> 
> What OS/GPU do you have?

Windows 10/ GTX 3050 4GB

**Comment by westmancurtis** [comment] 2023-01-24 16:07
Same error on an 8GB card, Ubuntu.

**Comment by holynski** [comment] 2023-01-24 16:44
Hey, we added this to the readme recently, but our current version of the code requires 18+ GB of GPU VRAM. If you want to run it on a smaller card, you'll likely have to use one of the alternative methods shown at the bottom of the page here: https://github.com/timothybrooks/instruct-pix2pix#other-ways-of-using-instructpix2pix

Closing for now, but feel free to comment further.

**Closed by holynski** 2023-01-24 16:44 UTC

**Comment by wh33t** [comment] 2023-01-24 16:46
> Hey, we added this to the readme recently, but our current version of the code requires 18+ GB of GPU VRAM. If you want to run it on a smaller card, you'll likely have to use one of the alternative methods shown at the bottom of the page here: https://github.com/timothybrooks/instruct-pix2pix#other-ways-of-using-instructpix2pix
> 
> Closing for now, but feel free to comment further.

Thank you for the clarification. I wasn't sure it actually required 18GB+.

**Comment by holynski** [comment] 2023-01-24 16:46
There are probably some optimizations that could be made to our code to reduce memory usage, and we'd welcome anyone to submit a PR for that. In the meantime, the other links should work for smaller GPUs (and even CPUs!).

**Comment by wh33t** [comment] 2023-01-25 02:36
I am getting replies on reddit that people are able to use ip2p with much less vram than I have. I think there is something wrong our installs. I am doing some tests now. Will report back with my findings.

**Comment by n00mkrad** [comment] 2023-01-25 02:49
512x512 takes up **4.6 GB VRAM** on my Windows 10 machine.

Using a very basic python script utilizing the `Diffusers` pipeline.

**Comment by wh33t** [comment] 2023-01-25 02:51
> 512x512 takes up **4.6 GB VRAM** on my Windows 10 machine.
> 
> Using a very basic python script utilizing the `Diffusers` pipeline.

Yup, definitely something wrong with our installs. I wonder if it's clashing with my other AI installations or we just straight up installed it incorrectly.

**Comment by n00mkrad** [comment] 2023-01-25 02:59
More numbers for reference

1024x1024 = 11.6 GB

1280x1024 = 16.9 GB

1280x1280 = >23 GB (starts offloading to RAM at this point)

**Comment by wh33t** [comment] 2023-01-25 03:21
I am not sure what the issue is. 

I re-installed Anaconda and all of ip2p on a different drive (same computer though) and I got the same problem. Seems like lots of people have got this working just fine. I am asking people how they went about the install. Hopefully we can figure out what all of us have in common that makes it not work for us.

**Comment by GuyRens** [comment] 2023-01-25 08:54
Yes, I have the same issue when running in windows 10 on my  RTX A4000 . 
I tried for a few hours to solve the problem, but I am far from an expert. If someone could figure this problem out, I would be very appreciative :)

**Comment by wh33t** [comment] 2023-01-25 16:10
I think I know the answer to our problems. A chatted with a reddit user who got this working just fine on very tame hardware. He claimed he never installed the github version, but rather this specific version of it from here:

https://nmkd.itch.io/t2i-gui/devlog/480628/sd-gui-190-now-with-instructpix2pix

I hope it's OK I'm posting a link. Anyhow, I guess the nmkd version is slightly different than this Github version in some very important ways.

**Comment by Dreamz-Dziner** [comment] 2023-01-25 18:42
> I think I know the answer to our problems. I chatted with a reddit user who got this working just fine on very tame hardware. He claimed he never installed the github version, but rather this specific version of it from here:
> 
> https://nmkd.itch.io/t2i-gui/devlog/480628/sd-gui-190-now-with-instructpix2pix
> 
> I hope it's OK I'm posting a link. Anyhow, I guess the nmkd version is slightly different than this Github version in some very important ways.

Thank you man. I will definitely check that version.

**Comment by wh33t** [comment] 2023-01-25 18:44
> > I think I know the answer to our problems. I chatted with a reddit user who got this working just fine on very tame hardware. He claimed he never installed the github version, but rather this specific version of it from here:
> > https://nmkd.itch.io/t2i-gui/devlog/480628/sd-gui-190-now-with-instructpix2pix
> > I hope it's OK I'm posting a link. Anyhow, I guess the nmkd version is slightly different than this Github version in some very important ways.
> 
> Thank you man. I will definitely check that version.

Report back, let me know if it works for you on a 4GB 970!

**Comment by Dreamz-Dziner** [comment] 2023-01-25 18:55
> > > I think I know the answer to our problems. I chatted with a reddit user who got this working just fine on very tame hardware. He claimed he never installed the github version, but rather this specific version of it from here:
> > > https://nmkd.itch.io/t2i-gui/devlog/480628/sd-gui-190-now-with-instructpix2pix
> > > I hope it's OK I'm posting a link. Anyhow, I guess the nmkd version is slightly different than this Github version in some very important ways.
> > 
> > 
> > Thank you man. I will definitely check that version.
> 
> Report back, let me know if it works for you on a 4GB 970!

Hey, I checked the link you posted and realized that it is an install for NMKD SD GUI. Actually I tried that yesterday itself with their version. It does work. But I was actually looking for the dedicated GUI only for this instruct pix2pix.

**Comment by n00mkrad** [comment] 2023-01-25 19:02
> I think I know the answer to our problems. I chatted with a reddit user who got this working just fine on very tame hardware. He claimed he never installed the github version, but rather this specific version of it from here:
> 
> https://nmkd.itch.io/t2i-gui/devlog/480628/sd-gui-190-now-with-instructpix2pix
> 
> I hope it's OK I'm posting a link. Anyhow, I guess the nmkd version is slightly different than this Github version in some very important ways.

Yeah that's my GUI.

This is the code it uses: https://github.com/n00mkrad/stable-diffusion-cust/blob/eaeaf3e79dfac6e1b31748fa661a1175705278c2/sd_ip2p/ip2p_batch.py

It's really basic, it just loads a command/prompt list from JSON and then calls the Diffusers implementation in a loop.

**Comment by wh33t** [comment] 2023-01-25 19:03
> Hey, I checked the link you posted and realized that it is an install for NMKD SD GUI. Actually I tried that yesterday itself with their version. It does work. But I was actually looking for the dedicated GUI only for this instruct pix2pix.

Oh I see. So I guess all the people reporting to me on Reddit that it can work with less than 18GB of vram are using this other version, which is not quite what you and all of us here were expecting/hoping for. I guess we'll just have to be patient and wait for the optimizations.

Cheers!

**Comment by n00mkrad** [comment] 2023-01-25 19:41
> > Hey, I checked the link you posted and realized that it is an install for NMKD SD GUI. Actually I tried that yesterday itself with their version. It does work. But I was actually looking for the dedicated GUI only for this instruct pix2pix.
> 
> Oh I see. So I guess all the people reporting to me on Reddit that it can work with less than 18GB of vram are using this other version, which is not quite what you and all of us here were expecting/hoping for. I guess we'll just have to be patient and wait for the optimizations.
> 
> Cheers!

My god, will no one listen to me?

**I am not using some funky customized version. My GUI's code is based off of the original author's Colab notebook for InstructPix2Pix. There are no hacks, no workarounds, zero architectural changes. I literally just call the Diffusers pipeline.**

These lines are all you need to reproduce it:

```py
pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained("timbrooks/instruct-pix2pix", torch_dtype=torch.float16, revision="fp16", safety_checker=None)
pipe.to("cuda")
pipe.enable_attention_slicing()

image = PIL.Image.open("./example.png")
image = PIL.ImageOps.exif_transpose(image)
image = image.convert("RGB")
image

image = pipe("turn it into a picasso painting", image=image).images[0]
image.save("./example-out.png")
```

> this other version, which is not quite what you and all of us here were expecting/hoping for.

Again I do NOT understand what you're trying to imply here. What are you hoping for that my (aka literally the original) code does not do?

Sorry for the rant but it feels like I'm talking to a wall here.

**Comment by n00mkrad** [comment] 2023-01-25 19:51
Should be mentioned that my VRAM tests were done with https://github.com/huggingface/diffusers/commit/f4dddaf5ee3ea784a700676abe2d48c9fc3feecf

**Comment by wh33t** [comment] 2023-01-25 19:53
> Sorry for the rant but it feels like I'm talking to a wall here.

I barely understand what your entire post means (total noob). I don't know if that code you posted should be added to a python script and executed with python, if that code is meant to replace something else in the ip2p root, can it be run from my local machine? You know what I mean? To someone who doesn't understand how any of this magic works it's very difficult to know what to do with the advice. 

> What are you hoping for that my (aka literally the original) code does not do?

I can't speak for everyone else here, but what I was hoping for was to be able to follow the quickstart instructions, run python edit_app.py, go to localhost:7860 and use the webGUI to change around some images.

**Comment by Dreamz-Dziner** [comment] 2023-01-25 21:16
> > Sorry for the rant but it feels like I'm talking to a wall here.
> 
> I barely understand what your entire post means (total noob). I don't know if that code you posted should be added to a python script and executed with python, if that code is meant to replace something else in the ip2p root, can it be run from my local machine? You know what I mean? To someone who doesn't understand how any of this magic works it's very difficult to know what to do with the advice.
> 
> > What are you hoping for that my (aka literally the original) code does not do?
> 
> I can't speak for everyone else here, but what I was hoping for was to be able to follow the quickstart instructions, run python edit_app.py, go to localhost:7860 and use the webGUI to change around some images.

"Isn't this place where we ask for help regarding an issue related to this particular repo rather" Everything you pointed out here is perfectly put. I totally relate to that. As an automatic1111 user I would love to see this implemented there or else run this as a standalone GUI. Hope people who rant understand this.

**Comment by illtellyoulater** [comment] 2023-01-27 19:04
I have the same problem I am on a 12 GB GPU and I can't run the code I installed by cloning this repository and setting up the conda environment.
I tried scaling the example image first to 384, then to 256, then 128 up to 64x64 ... to see if there was a point at which it would  begin to start working... but it didn't... same old CUDA Memory Error problem.

So I took a look at these other implementation you are talking about including A1111's one... which I just installed.
I don't know why but for some reason the results it produces are nowhere near close to the original ip2p demo I tried on Hugging Face...
Not sure what is actually going on here... maybe I am just tired...

**Comment by wh33t** [comment] 2023-01-27 19:23
> I don't know why but for some reason the results it produces are nowhere near close to the original ip2p demo I tried on Hugging Face...

I'm guessing the actual ip2p implementation uses some primo CLIP interrogator to better understand what the image actually is.

Fwiw, tryout [n00mkrad](https://github.com/n00mkrad) implementation (windows only it seems), people on Reddit seem to be having good fun with it, even on lower spec hardware. https://nmkd.itch.io/t2i-gui/devlog/480628/sd-gui-190-now-with-instructpix2pix

**Comment by illtellyoulater** [comment] 2023-01-27 20:06
No it's my bad actually... I'm definitely too tired... I was not loading the ip2p model in A1111's UI but I was going with the default SD 1.5 😓 ... but in my defense I can say that since I had previously used this repo "download_checkpoints.sh" to download the model weights, I gave for granted they were downloaded to the usual "~/.cache/huggingface/" dir, so when I later switched to try A1111 extension and it didn't complain about missing the model during the installation or even after it I just automatically assumed it was picking them up from that dir... and then it went as it went... 😑🐸

Anyway, now that the mystery is solved I'll play around with it and see how fun it will get... 😎
